### ISSUE TITLE
error when runing train_full_rl in my own dataset

### ISSUE THREAD

**Issue by ShawnXiha** [ChenRocks/fast_abs_rl#17]
`WARNING: Exploding Gradients 8048.54
WARNING: Exploding Gradients 219.81
WARNING: Exploding Gradients 360.95
WARNING: Exploding Gradients 233.41
Traceback (most recent call last):
  File "train_full_rl.py", line 228, in <module>
    train(args)
  File "train_full_rl.py", line 182, in train
    trainer.train()
  File "/data/xiaqiang/nmt/fast_abs_rl/training.py", line 211, in train
    log_dict = self._pipeline.train_step()
  File "/data/xiaqiang/nmt/fast_abs_rl/rl.py", line 174, in train_step
    self._stop_reward_fn, self._stop_coeff
  File "/data/xiaqiang/nmt/fast_abs_rl/rl.py", line 101, in a2c_train_step
    critic_loss = F.mse_loss(baseline, reward)
  File "/data/xiaqiang/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1716, in mse_loss
    return _pointwise_loss(lambda a, b: (a - b) ** 2, torch._C._nn.mse_loss, input, target, reduction)
  File "/data/xiaqiang/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1674, in _pointwise_loss
    return lambd_optimized(input, target, reduction)
RuntimeError: input and target shapes do not match: input [204], target [200] at /opt/conda/conda-bld/pytorch_1535491974311/work/aten/src/THCUNN/generic/MSECriterion.cu:12
`

**Comment by amobash2** [comment]
hey, I have the same problem, did you have a chance to fix this?

**Comment by amobash2** [comment]
@zhengwsh , I think Exploring Gradients warning is fine in this place (let me know if you think otherwise), in rl.py, "if max_grad is not None and grad_norm >= max_grad:" then "grad_norm" is set to "max_grad". I had the same error too.

**Comment by Zerone0101** [comment]
i meet the same 'exploding gradients' warnings problem as described in zhengwsh 
Is this 'exploding gradients' often met in reinforce learning training process ?
or is there any theory or practical explanations about the 'exploding gradients' ?

**Comment by amobash2** [comment]
@Zerone0101, yep, exploding and vanishing gradients are both issues happening in calculating gradients in NN (specially very deep NN), you can refer to: https://machinelearningmastery.com/exploding-gradients-in-neural-networks/ and many papers suggesting approaches to deal with exploding gradients such as using LSTM and gradient clipping.

**Comment by ChenRocks** [comment]
This is a research code base and I did not plan for customized dataset. If the error is not from the original CNN/DM I'm afraid I can't help.

Exploding gradient is a warning that you probably need to tune some hyper parameters to make training stable. How to fix this is usually case-by-case. I will keep this issue open for now for public discussions.

**Comment by ChenRocks** [comment]
closing due to no further discussions
