### ISSUE TITLE
How to utilize the results form the extractor? 

### ISSUE THREAD

**Issue by hyejin-min** [ChenRocks/fast_abs_rl#19]
Thanks for the great work! 
I'm just wondering if we can utilize the results form the extractor independently.

**Comment by ChenRocks** [comment]
Thanks for your interest! Feel free to create a fork for your own customization. You can start by creating a 'dummy abstractor' and run extractor and RL training.

**Comment by ChenRocks** [comment]
closing due to no further discussion
