### ISSUE TITLE
Why need to remove the last id of target?

### ISSUE THREAD

**Issue by chenhuaizhen** [ChenRocks/fast_abs_rl#20]
https://github.com/ChenRocks/fast_abs_rl/blob/aebf539107caba5be35720f5d1f9f98989a069e8/data/batcher.py#L170
Hi, I found in batcher.py there exist one line that remove the last id of the target, but I am very puzzle why do this, can you kindly explain it for me?

**Comment by chenhuaizhen** [comment]
I think I know why, due to it uses Pointer Net, it needs to remove the last id and add the init-state in the first space(just like right shift) to turn into the input of the net, and its expect output is its oringinal id-sequence.

**Comment by zhengwsh** [comment]
@chenhuaizhen  what does "the last id of the target" means? does it represent the last sentence of abstracts/targets?

**Comment by chenhuaizhen** [comment]
@zhengwsh 
First question: Due to the task of this project is to produce abstract with several sentences, its final target is like [t1,t2,...,tn] in the train_extractor_ml ( tn means the index of the sentence of the article which is mostly like the nth sentence of the abstract ). Due to it uses the Pointer Net, your input just like [init_state, t1, t2, ..., tn-1], and your label is like [t1, t2, t3, ..., tn]

Seconde question: if you just run this code you will meet some problems, you can try to fix it just like below:
change
https://github.com/ChenRocks/fast_abs_rl/blob/aebf539107caba5be35720f5d1f9f98989a069e8/data/batcher.py#L170
to:
```python
def remove_last(tgt):
    tgt[1:] = tgt[:-1]
    return tgt
```
change
https://github.com/ChenRocks/fast_abs_rl/blob/aebf539107caba5be35720f5d1f9f98989a069e8/model/extract.py#L186
to:
```python
lstm_in[:,0,:] = init_i.squeeze(1)
lstm_in = lstm_in.transpose(0, 1)
```

So in this new code you will no need to remove the first sentence to make your all targets become null sets which may cause some problems and it follows the original principle.

**Comment by zhengwsh** [comment]
@chenhuaizhen Grateful for your clear explanation and valuable suggestions.
