### ISSUE TITLE
invalid gradient at index 0 - expected shape [] but got [1]

### ISSUE THREAD

**Issue by amobash2** [ChenRocks/fast_abs_rl#21]
Hi,

I am new to pytorch, and was trying to use your model for summarizing some text. I have been trying to run training with news data, and then added only a single new file, in both cases, train_full_rl fails in rl.py file with below error, I tried to switch to GPU and still get same problem, I was wondering if you have seen this error before. When I was using GPU, it would show error that input and target size does not match, that is why I am printing out sizes (torch.Size([700])):

{'net_args': {'extractor': {'net_args': {'conv_hidden': 100, 'emb_dim': 128, 'bi                                                                                                                                                             directional': True, 'vocab_size': 30004, 'lstm_layer': 1, 'lstm_hidden': 256}, '                                                                                                                                                             traing_params': {'batch_size': 32, 'lr_decay': 0.5, 'optimizer': ['adam', {'lr':                                                                                                                                                              0.001}], 'clip_grad_norm': 2}, 'net': 'ml_rnn_extractor'}, 'abstractor': {'net_                                                                                                                                                             args': {'emb_dim': 128, 'bidirectional': True, 'vocab_size': 30004, 'n_hidden':                                                                                                                                                              256, 'n_layer': 1}, 'traing_params': {'batch_size': 32, 'lr_decay': 0.5, 'optimi                                                                                                                                                             zer': ['adam', {'lr': 0.001}], 'clip_grad_norm': 2.0}, 'net': 'base_abstractor'}                                                                                                                                                             }, 'train_params': {'gamma': 0.95, 'lr_decay': 0.5, 'stop_reward': 'rouge-1', 'c                                                                                                                                                             lip_grad_norm': 2, 'batch_size': 32, 'reward': 'rouge-l', 'optimizer': ('adam',                                                                                                                                                              {'lr': 0.0001}), 'stop_coeff': 1.0}, 'net': 'rnn-ext_abs_rl'}
Start training
torch.Size([700])
torch.Size([700])
Traceback (most recent call last):
  File "Geneva_ABS.py", line 266, in <module>
    main(args)
  File "Geneva_ABS.py", line 224, in main
    train_full_rl().train(path=output_path+'/model/', abs_dir=output_path+'/abst                                                                                                                                                             ractor/', ext_dir = output_path+'/extractor/')
  File "/home/train_full_rl.py", line 195                                                                                                                                                             , in train
    trainer.train()
  File "/home/training.py", line 211, in                                                                                                                                                              train
    log_dict = self._pipeline.train_step()
  File "/home/rl.py", line 177, in train_                                                                                                                                                             step
    self._stop_reward_fn, self._stop_coeff
  File "/home/rl.py", line 108, in a2c_tr                                                                                                                                                             ain_step
    [torch.ones(1).to(critic_loss.device)]*(1+len(losses))
  File "/home/venv/lib/python3.5/site-packages/torch/autograd/__in                                                                                                                                                             it__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: invalid gradient at index 0 - expected shape [] but got [1]

**Comment by amobash2** [comment]
Oh it seems another person had same problem probably:

https://github.com/ChenRocks/fast_abs_rl/issues/17

**Comment by chenhuaizhen** [comment]
I have met this problem too, and that's how I fix it:
change
https://github.com/ChenRocks/fast_abs_rl/blob/aebf539107caba5be35720f5d1f9f98989a069e8/rl.py#L103
to
```python
[critic_loss.unsqueeze(0)] + losses
```
this problem will happen when critic_loss is a number not an array.

**Comment by amobash2** [comment]
@chenhuaizhen comment is the fix for the issue.

**Comment by jlbhdfsl** [comment]
I solve it by this:
# backprop and update
# the critic_loss is a float but the losses is a list of tensor in shape [1]!!
# they the critic_loss and the losses need different type of gradient one is a tensor(1.0)
# the other is a ones(1)
autograd.backward(
        [critic_loss] + losses,
        [torch.tensor(1.0).to(critic_loss.device)] +
        [torch.ones(1).to(critic_loss.device) for _ in losses]
    )
