### ISSUE TITLE
russian data

### ISSUE THREAD

**Issue by vtrokhymenko** [ChenRocks/fast_abs_rl#31]
Hi,

With your repo, I want to create own model to do summarization article to the title in my data.
How u think, when I have done this with your repo, the result had been similar?

Plus, how I should prepare my data?

**Comment by ChenRocks** [comment]
Please check [this repository](https://github.com/ChenRocks/cnn-dailymail) for data preprocessing. Feel free to create PR when you're done :)
Thanks!

**Comment by ChenRocks** [comment]
closing due to no further discussion
