### ISSUE TITLE
How to get the extractive summary

### ISSUE THREAD

**Issue by Zierzzz** [ChenRocks/fast_abs_rl#32]
Hello, I can train the model, I just get a label of extractor, but I can't find how to get the first phrase extrator summay .Could you tell me how to fix it?

**Comment by ChenRocks** [comment]
Please refer to the paper to better understand how extractor/abstractor works. I don't quite understand your questions. Feel free to reply further details and I'll try my best to help.

**Comment by ChenRocks** [comment]
closing due to no further discussion.
