### ISSUE TITLE
[Question] Why not ff-ext with RL ?

### ISSUE THREAD

**Issue by Colanim** [ChenRocks/fast_abs_rl#33]
From the results of your paper : 

![image](https://user-images.githubusercontent.com/43774355/54335082-3835b680-466b-11e9-8405-c00facc09baf.png)

For both abstractive and extractive approach, it seems that :

**`ff-ext` > `rnn-ext`**

---

Why not comparing `ff-ext + RL` and `ff-ext + RL + rerank` with other approaches as well ?

**Comment by ChenRocks** [comment]
When I develop the model I can't think of a good way to apply RL with feed-forward structures due to lack of a memory hidden state as in RNNs. Feel free to try your own experiments based on this code. When you have better results and publish a paper please do consider citing our work :)
