### ISSUE TITLE
[Question] Apply the code to other datasets ?

### ISSUE THREAD

**Issue by Colanim** [ChenRocks/fast_abs_rl#35]
I would like to apply this great code to other datasets, but I met several obstacles :

1. The article is not sentence-separated
2. The summary is a single sentence, representing several sentences of the article

---

To overcome these obstacles, I tried following approach :

1. Use a sentence tokenizer (SpaCy) to process the dataset before training. 
2. As mentioned by #4, extract K sentences and concatenate them into a single sentence to the abstractor.

---

But it's not a good approach. 

First of all, the sentence tokenizer is not perfect and tokenized sentences might be messed up.

About the dataset with a single sentence, most of the time this sentence is very abstractive. Therefore, creating the pseudo-labels is difficult. I believe in this case the ROUGE-L matching might not give the best corresponding sentence.
And if the pseudo-labels are wrong...

---

So my question is : **do you have any lead of general idea that I can implement to improve the existing code for other datasets ?**

**Comment by ChenRocks** [comment]
Thanks for your interest in our research. I think the points you mentioned are interesting questions to solve.

I think spacy tokenizer might not be the best choice. You could probably start with something even simpler such as [nltk](https://www.nltk.org/api/nltk.tokenize.html#module-nltk.tokenize.punkt).
About the abstractiveness problem this is indeed an issue. One idea is to try METEOR score since it supports some synonym/phrase match. Note that highly abstractive summrization is still a difficult open research problem.
However, our paper aims to solve the long-summary problem so in your case (summary is only one sentence) it might not be the best summarization algorithm in the first place.

I hope the answer is helpful to your research.

**Comment by Colanim** [comment]
I tried to _extract K sentences and concatenate them into a single sentence, fed to the abstractor_ in order to adapt this architecture to others datasets, where a single sentence might be constructed from several passage of the article.

... And it's a fail. The extractor works like a charm, extract several sentences, separated by a special token. But abstractor simply copy the first extracted sentence.

Possible explanation of such a behavior :

### The way to make pseudo-labels is wrong

I did like you, using rouge score between the summary sentences and article sentences. But instead of extracting the best one, I extracted the K best ones. This seems the right approach. 

But let's say that half of the summary sentences are constructed from a single sentence. In that case, we have :

> sen_A, sen_B, sen_C  --->  sen_A'B'C'
 
half of the time, and other half we have :

> sen_A, sen_B, sen_C  --->  sen_A'

Which means that in half of the case, abstractor will be trained to ignore supplementary extracted sentences.

**I need another way to create the pseudo-labels, where K vary depending on each sentence.**

---

@ChenRocks any idea on how to improve this ?

---

Also, I noticed that the sentence produced by the abstractor are mere copy of the extracted sentence. 

I'm not sure about this one, is it because the sentence of the dataset I use are too abstracted and during training the abstractor can't find a better way than simply copying the input ?

I use the Newsroom dataset.

**Comment by ChenRocks** [comment]
I am not familiar with the newsroom dataset and I'm afraid I can't help much. Your questions are open research problems to solve and you might need more novel ideas for it.

For the copying issue, I think this is the problem of [pointer-generator network](https://arxiv.org/abs/1704.04368) for summarization. Maybe some recent papers start trying to address this "lack of novelty" issue. Unfortunately I don't have a good way to solve it.
