### ISSUE TITLE
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by kFoodie** [ChenRocks/fast_abs_rl#36]
RuntimeError: CUDNN_STATUS_EXECUTION_FAILED
![image](https://user-images.githubusercontent.com/16017418/55077883-c41bf980-50d3-11e9-9395-747aa3fb3fe0.png)
ubuntu 16.0.4
pytorch 0.4.0
python 3.6.5
cuda 9.0
##########
what should I do..

**Comment by tjzjp** [comment]
I have the same problem, have you fixed it?

**Comment by ChenRocks** [comment]
Hi, it seems to me this is not problem from my repository.

Please test with something like:
```python
import torch
lstm = torch.nn.LSTM(4, 4, 1)
lstm.cuda()
```
to see if the same error occurs.

I once see this same problem and I end up reinstalling pytorch and it was fixed. If it is indeed a pytorch/cudnn problem I'm afraid I can't help much.

**Comment by ChenRocks** [comment]
Also @kFoodie I noticed you are using GPU1 from your screenshot. Will use GPU0 fix the issue?

**Comment by kFoodie** [comment]
I have solve this problem by install cuda10 and install cuda10-pytorch1.0.0

**Comment by kFoodie** [comment]
thanks

**Comment by ChenRocks** [comment]
closing this issue.
@tjzjp you could probably also try to reinstall cuda/pytorch.
