### ISSUE TITLE
[Clarification] Why EOE is trained only at RL time ?

### ISSUE THREAD

**Issue by Colanim** [ChenRocks/fast_abs_rl#38]
I understand that EOE token allow the agent to stop in RL training.

But why not training also the extractor (only) to extract EOE token ? 

---

I'm trying to add another token into your architecture, and follow your design by adding it only at RL.

However results are not satisfying. I'm wondering if I should train the extractor too, with this supplementary token.

What do you think ?

**Comment by ChenRocks** [comment]
Yes it is possible to add EOE in ML-trained extractor. In the early stage of this project we were just trying to get the better initialization of the ConvNet and LSTMs in the extractor and we wanted to tune a fix number of sentence for generation on the validation set. Later we had this EOE idea to dynamically decide the number of output sentences but we did not go back to modify train_extractor. We found the ConvNet and LSTMs are initialized well enough and EOE does learn to dynamically stop so we stick to this architecture.

Seems like you are working on a different dataset so I would say modifying the non-RL extractor is definitely worth to try. I am guessing you want to add some different `actions` to your model. My general advise is to make sure your RL reward is meaningful w.r.t the action (for example, output length is definitely related to ROUGE-L reward) so the model learns when is best to choose the action.

**Comment by Colanim** [comment]
Thanks for your precious insights, it's really helpful.

One more thing (related) I didn't fully understand :

**How do you prevent the extractor to extract too much ?**

---

As you guessed, I'm working with a different dataset : I'm trying to input several sentences to the abstractor, and try to make it abstract theses sentences into a single sentence.

In that case, I'm not sure how to prevent the extractor to extract too much sentence. 

In your case, if the extractor extract too much sentences, you put 0 reward for the supplementary sentences, and the stop reward will make the extractor learn to not predict too much (because rouge-n would decrease in that case).

But in my case, the number of sentences extracted cannot be controlled easily : maybe the extractor will extract 10 sentences instead of 2 and still the abstractor will produce a ok-summary regarding to rouge-l, but completely clumsy for a human.

**Comment by Colanim** [comment]
My bad, I didn't read the detail of your paper :

![image](https://user-images.githubusercontent.com/43774355/55461412-5457c280-562f-11e9-81e0-de0cfe613753.png)

![image](https://user-images.githubusercontent.com/43774355/55461430-620d4800-562f-11e9-9441-902d319b391b.png)
