### ISSUE TITLE
about the paper

### ISSUE THREAD

**Issue by NiceMartin** [ChenRocks/fast_abs_rl#39]
Hi Chen,
    I read your paper, which is very interesting.  I have several questions; could you please help me figure them out ?

1. The extractor extracts salient sentences (d_1,d_2,...d_n) from the original documents. For each salient sentence, the abstractor function (g) generate a summary sentence; all the summary sentences are concatenated to form the entire summary. 
   I am wondering if my understanding is correct. 

2. In the paragraph above section 2.1, I am wondering if this is a typo?
<img width="397" alt="屏幕快照 2019-04-03 下午4 58 06" src="https://user-images.githubusercontent.com/37323585/55466417-b44f6880-5631-11e9-82d4-e112ce6c904d.png">
S_i should be set of summary sentences in y_i while D_i is the set of document sentences in x_i
    
Thanks

**Comment by ChenRocks** [comment]
Thanks for your interest in the paper!
1. yes you are correct
2. good eyes! I will update the arxiv paper soon.

**Comment by NiceMartin** [comment]
Thanks, Chen !
