### ISSUE TITLE
when my dataset is  single sentence abstract.

### ISSUE THREAD

**Issue by BIGKUANG** [ChenRocks/fast_abs_rl#4]
Dear Chen 
  I train this model in othe dataset of  single sentence abstract. but  in the process of implementation, i find that the model(abstractor) build an channel by single sentence to single abstract. 
  If i try to intelligently select K sentence by rouge in extractor stage, than i flatten this sentence to train in abstractor and full_rl, do you think  this is feasible？
  Does the model of fast_abs_rl  apply to  single sentence abstract? I would be very grateful  for your reply and advices.

**Comment by ChenRocks** [comment]
Thanks for your interest in using our code. Please read the full paper for the rationale on why we select K sentences then output abstract.

In short, we extract K sentences and then decode K abstract sentences independently. In the experiment we found this is beneficial for multi-sentence summary task. I'm not sure about your task/dataset so it's difficult for me to give advice.

Feel free to fork the repository and then build upon our model for your own experiments.

**Comment by ChenRocks** [comment]
closing this due to no further discussion

**Comment by Colanim** [comment]
@BIGKUANG

> If i try to intelligently select K sentence by rouge in extractor stage, than i flatten this sentence to train in abstractor and full_rl

Did you try this approach ? How are the results ?
