### ISSUE TITLE
attention for LSTMPointerNet - self._attn_wm is not used

### ISSUE THREAD

**Issue by richcmwang** [ChenRocks/fast_abs_rl#40]
Hi,

Thanks for sharing the excellent work and high-quality code!  I notice in the attention mechanism for `LSTMPointerNet`, you didn't use `self._attn_wm` in `attention_score` function.  I guess the result is already good without it.  Did you decide to drop `self._attn_wm` because it does not help much?  Thanks for the comments.

**Comment by ChenRocks** [comment]
It is used [here](https://github.com/ChenRocks/fast_abs_rl/blob/aebf539107caba5be35720f5d1f9f98989a069e8/model/extract.py#L222) for efficiency. `attention_score` would be called multiple times but in `_prepare` we can transform all the hidden representations at once. Hope the explanation helps, thanks!
