### ISSUE TITLE
`bidirectional` for StackedLSTMCells and a typo(?)

### ISSUE THREAD

**Issue by richcmwang** [ChenRocks/fast_abs_rl#42]
I notice two unusual places of codes, and was puzzled by that.

(1) in `class StackedLSTMCells` in rnn.py
line 102
 @property
   def bidirectional(self):
        return self._cells[0].bidirectional    #  ==> LSTMCell has no bidirectional?

I suppose `self._cells` stores `nn.LSTMCell`, which has no `bidirectional` attribute?  Do I understand this correctly?

(2) In `class _CopyLinear` in copy_summ.py

inside `__init__` function, I notice a line:
`self.regiser_module(None, '_b')`.  Do you mean `register_module`?  
If I set `bias=False`, I will get an error either way.  Could you comment on this?

Thank you!

**Comment by ChenRocks** [comment]
(1) I design this API in case there is a BidirectionalCell in the future. This seems not happening so it probably should just return False.
(2) yes it is typo, although I would not set the bias to False.

**Comment by ChenRocks** [comment]
For (2) it actually should be `register_parameter`

**Comment by richcmwang** [comment]
Thanks for the clarification!
