### ISSUE TITLE
Using a different word embedding model

### ISSUE THREAD

**Issue by nickluijtgaarden** [ChenRocks/fast_abs_rl#47]
Hey Chen,

Recently, a very interesting model called BERT (https://github.com/google-research/bert) came out and has shown to achieve novel results on several NLP tasks. Do you think the results of your model can be improved by using their embedding model instead of word2vec?

I think it is an interesting idea, but I think I would need to make many many changes to the current architecture of your model.

Kind regards,

Nick

**Comment by ChenRocks** [comment]
As you mentioned, it requires a big change to make things work. From my viewpoint, BERT is not just some fixed embedding. Instead, SotA performance can only be achieved when finetuned on the target task. So far there is only limited success of BERT on NLG tasks so it is hard to tell whether it can improve summarization. This is an interesting open research problem. Feel free to use this project as a starting point of new research.
