### ISSUE TITLE
Bug when limiting the number of sentences in the summary

### ISSUE THREAD

**Issue by fnan** [ChenRocks/fast_abs_rl#48]
When I limit the number of sentences in the summary to 1, for example, the `forward` function in `PtrExtractorRL` in `/model/rl.py` is called. 
The for loop `for _ in range(n_step):` is run once (`n_step=1`) and the output is returned. 
Yet in `decode_full_model.py` the last element of the extracted output is removed as EOE: 
` ext = extractor(raw_art_sents)[:-1] # exclude EOE`.

So in this case the only sentence being extracted is discarded as EOE. 

One solution I can think of is to append an EOE in the `forward` function of `PtrExtractorRL`. Specifically, insert the following lines just before the return call:
```
if out.item() != score.size()[1]:
    append(torch.tensor([[score.size()[1]]], device=out.get_device()))
```

**Comment by ChenRocks** [comment]
You should use `PtrExtractorRLStop`. `PtrExtractorRL` is developed before I came out with the EOE action idea. Since models with EOE work much better I did not maintain a version without it.
