### ISSUE TITLE
No beam search during training

### ISSUE THREAD

**Issue by zfang** [ChenRocks/fast_abs_rl#5]
Hello,

Could you help me understand why beam search (e.g. `BeamAbstractor`) is not used during training (either abstractor training or RL training)?

Thanks,

Felix

**Comment by zfang** [comment]
I think I understand why beam search is not used during abstractor training: we want to train a good abstractor without the postprocessing step. Fo RL training, since the abstractor is only used for inference, doesn't using beam search give a better estimate of reward for the extractor?

**Comment by ChenRocks** [comment]
The reason of not using beam-search is our empirical finding. We found that using by greedy decoding the performance is already good enough and much faster. Using beam-search w/o reranking doesn't give improvements on the final performance. Please refer to the paper for how to use beam-search and reranking to boost the ROUGE score.

**Comment by ChenRocks** [comment]
closing this due to no further discussion
