### ISSUE TITLE
Is there a way to train on datasets other than CNN/Daily Mail

### ISSUE THREAD

**Issue by Rushab1** [ChenRocks/fast_abs_rl#50]
Since the preprocessing assumes that the model is going to be run on CNN or Daily Mail. Can this be run on other datasets with minimal changes?

Specifically, is it possible to use pre-trained models on other datasets with minimal changes to the code, or would there have to be too many changes?

**Comment by nickluijtgaarden** [comment]
Hi Rushab1,

I am currently using this model on a new dataset. My implementation can be found on the following repository: https://git.science.uu.nl/n.vandeluijtgaarden/legal-text-summarization/tree/develop

Yes, you can use their pre-trained models on a new dataset, but you will have to tokenize this dataset first and put it in the right format. I think my documentation does a good job of explaining this. A few changes are necessary, but not that much to be honest. You can also train the model on a new dataset, which I did in my case.

**Comment by Rushab1** [comment]
@nickluijtgaarden Thanks! I'll check it out

**Comment by ChenRocks** [comment]
Thanks for sharing @nickluijtgaarden.

I'm closing the issue since I don't plan to support other datasets.
