### ISSUE TITLE
is there a way to extract a fixed number of summary sentences?

### ISSUE THREAD

**Issue by jawdat23** [ChenRocks/fast_abs_rl#51]
Hey,
Thanks for this great work, I just want to know if it is easily possible to force the model to predict exactly n abstract lines, so all tested articles will have the same number of summary lines.

**Comment by ChenRocks** [comment]
Predicting different number of sentences dynamically is one of the novelty of our paper. You can manually truncate them / force EOE on you own. Thanks.
