### ISSUE TITLE
Computing abstractiveness

### ISSUE THREAD

**Issue by nickluijtgaarden** [ChenRocks/fast_abs_rl#54]
In your paper you mentioned an interesting statistic, the abstractiveness of the model. You compute an abstractiveness score (See et al.,2017) as the ratio of novel n-grams in the generated summary that are not present in the input document.

Can you share the code that is used to re-produce this experiment?

Thanks in advance,

Nick

**Comment by ChenRocks** [comment]
Thanks for your interest. Unfortunately I can't find the old code as of now. I believe it is very straightforward to implement. The n-gram follows the same tokenization w/o any extra text normalization. So you can compute all the n-grams (n=1~4) for the document and summary and then compute the overlap divided by total summary n-gram. Please let me know if you need extra clarification.
