### ISSUE TITLE
Decoding stuck at the 1320th json input

### ISSUE THREAD

**Issue by skydiving94** [ChenRocks/fast_abs_rl#57]
Hi! I am trying to summarize some text files (not from the cnn daily mail dataset) using your decode_full_model.py. When the number of files is not very big, i.e. around 1000, it was working perfectly fine. However, because I have in total around 1 million files to summarize, the decoding process got stuck at the 1320th file. I tried to restart the decode multiple times and each time it was stuck at the same file. You can see the outputs from the screenshot below.
![image](https://user-images.githubusercontent.com/7350056/62146745-a2b65e80-b2bb-11e9-83c5-56126c11faab.png)

I am wondering what could cause it. I did not modify the code but instead pre process my files so that they have the same structures as the one suggested on the website.

**Comment by nickluijtgaarden** [comment]
Hi!

Decoding seems to have some issues at beam > 1, because when summaries have
> 20 sentences, the reranking needs to do too many calculations and just
gets stuck.

My solution was too only take the first 20 sentences for the summary and
skip the last ones when decoding. On holiday right now, but I can share my
code later if you want.

Kind regards,

Nick

Op di 30 jul. 2019 09:45 schreef Timo Wang <notifications@github.com>:

**Comment by skydiving94** [comment]
Thank you for your response! 

I checked the config I was using and can confirm that my beam was set to be 1. However, it can be an issue that the documents to summarize can be long. Could you maybe suggest where I can modify the code so that only the first 20 sentences are taken for summary? I will give a it a try then.

Thanks again!

**Comment by nickluijtgaarden** [comment]
You can check out my branch here:

https://git.science.uu.nl/n.vandeluijtgaarden/legal-text-summarization/tree/develop/models/chen_bansal_2018

It is somewhere in the decoding functions that I made the changes. Cheers!

 di 30 jul. 2019 17:24 schreef Timo Wang <notifications@github.com>:

**Comment by skydiving94** [comment]
Great! Thanks a lot!

Holen Sie sich Outlook für Android<https://aka.ms/ghei36>

________________________________

**Comment by ChenRocks** [comment]
Thanks for the solution.
