### ISSUE TITLE
Why A2C ?

### ISSUE THREAD

**Issue by astariul** [ChenRocks/fast_abs_rl#58]
I was wondering the exact reason why you chose A2C for RL training.

For example, why not using self-critical policy gradient as described in [this paper](https://arxiv.org/pdf/1705.04304.pdf) (Section 3.2). From my inexperienced point of view, it seems better as you don't have to bother training a Critic.

---

**So why choosing A2C specifically ?**

* Did you compare this algorithm with other alternatives ? If yes what are the reason to choose A2C ?
* Or did you simply tried it and since it worked and is widely used you decided to use it too ?

**Comment by ChenRocks** [comment]
Yes I chose A2C because it worked (vanilla PG didn't). If it hadn't worked I would probably implement self-critical training. The idea is still using RL in extraction rather than word-level generation.
Thanks.
