### ISSUE TITLE
TypeError: prepro_fn_extract() missing 1 required positional argument: 'batch'

### ISSUE THREAD

**Issue by lagka** [ChenRocks/fast_abs_rl#59]
when i run  train_extractor_ml.py I encountered this problem , as the error mentioned , it seems that prepro_fn_extract function need one more argument "batch" . But there is no such argument pass through .

**Comment by ChenRocks** [comment]
[prepro_fn_extract](https://github.com/ChenRocks/fast_abs_rl/blob/b1b66c180a135905574fdb9e80a6da2cabf7f15c/data/batcher.py#L48) is a curry function. Did you modify the code?

**Comment by lagka** [comment]
I do modify some code , and I found that I delete "@curry" symbol .
Thanks for you help.
