### ISSUE TITLE
About ROUGE for evaluations.

### ISSUE THREAD

**Issue by zhouqiji** [ChenRocks/fast_abs_rl#7]
Hi, 
I followed the institution to install and set pyrouge and ROUGE1.5.5,
when I evaluate the full model by executing the "eval_full_model.py" script, the --meteor flag works well, but the --rouge flag will output errors like:

Cannot open exception db file for reading: /home/zqj/Workspace/Tools/pyrouge-master/tools/ROUGE-1.5.5/data/WordNet-2.0.exc.db
Traceback (most recent call last):
  File "eval_full_model.py", line 53, in <module>
    main(args)
  File "eval_full_model.py", line 26, in main
    output = eval_rouge(dec_pattern, dec_dir, ref_pattern, ref_dir)
  File "/home/zqj/Workspace/fast_abs_rl/evaluate.py", line 40, in eval_rouge
    output = sp.check_output(cmd.split(' '), universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/zqj/Workspace/Tools/pyrouge-master/tools/ROUGE-1.5.5/ROUGE-1.5.5.pl', '-e', '/home/zqj/Workspace/Tools/pyrouge-master/tools/ROUGE-1.5.5/data', '-c', '95', '-r', '1000', '-n', '2', '-m', '-a', '/tmp/tmpf5fnmfg3/settings.xml']' returned non-zero exit status 255

My OS  is: Ubuntu 16.04.
Perl version: perl 5, version 22.

My I ask how to solve this is issue?

**Comment by ChenRocks** [comment]
Please check this [page](http://kavita-ganesan.com/rouge-howto/#.W1l1-i2ZORc) and read the *WordNet Exception* paragraph. Hope this helps.

**Comment by ChenRocks** [comment]
closing this since it's more of a ROUGE issue rather than issue of this repository.
