### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory 

### ISSUE THREAD

**Issue by QuietWoods** [ChenRocks/fast_abs_rl#8]
(train the full RL model)
I am trying to run python train_full_rl.py --path=[path/to/save/model] --abs_dir=[path/to/abstractor/model] --ext_dir=[path/to/extractor/model]
My GPU has 12GB memory.  NVIDIA-SMI 387.26 , Driver Version: 387.26  
0  Tesla K40m . 
Could you comment on how much GPU RAM does training this needs in the README?
Thank you! 
I met such error:

loading checkpoint ckpt-1.482692-6000...
loading checkpoint ckpt-3.515528-3000...
loading checkpoint ckpt-1.482692-6000...
start training with the following hyper-parameters:
{'net': 'rnn-ext_abs_rl', 'net_args': {'abstractor': {'net': 'base_abstractor', 'net_args': {'vocab_size': 30004, 'emb_dim': 128, 'n_hidden': 256, 'bidirectional': True, 'n_layer': 1}, 'traing_params': {'optimizer': ['adam', {'lr': 0.001}], 'clip_grad_norm': 2.0, 'batch_size': 32, 'lr_decay': 0.5}}, 'extractor': {'net': 'ml_rnn_extractor', 'net_args': {'vocab_size': 30004, 'emb_dim': 128, 'conv_hidden': 100, 'lstm_hidden': 256, 'lstm_layer': 1, 'bidirectional': True}, 'traing_params': {'optimizer': ['adam', {'lr': 0.001}], 'clip_grad_norm': 2.0, 'batch_size': 32, 'lr_decay': 0.5}}}, 'train_params': {'optimizer': ('adam', {'lr': 0.0001}), 'clip_grad_norm': 2.0, 'batch_size': 32, 'lr_decay': 0.5, 'gamma': 0.95, 'reward': 'rouge-l', 'stop_coeff': 1.0, 'stop_reward': 'rouge-1'}}
Start training
WARNING: Exploding Gradients 1829948160.00
WARNING: Exploding Gradients 110035.23
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "train_full_rl.py", line 228, in <module>
    train(args)
  File "train_full_rl.py", line 182, in train
    trainer.train()
  File "/home/project/fast_abs_rl/fast_abs_rl/training.py", line 211, in train
    log_dict = self._pipeline.train_step()
  File "/home/project/fast_abs_rl/fast_abs_rl/rl.py", line 173, in train_step
    self._stop_reward_fn, self._stop_coeff
  File "/home/project/fast_abs_rl/fast_abs_rl/rl.py", line 64, in a2c_train_step
    summaries = abstractor(ext_sents)
  File "/home/project/fast_abs_rl/fast_abs_rl/decoding.py", line 94, in __call__
    decs, attns = self._net.batch_decode(*dec_args)
  File "/home/project/fast_abs_rl/fast_abs_rl/model/copy_summ.py", line 63, in batch_decode
    attention, init_dec_states = self.encode(article, art_lens)
  File "/home/project/fast_abs_rl/fast_abs_rl/model/summ.py", line 81, in encode
    init_enc_states, self._embedding
  File "/home/project/fast_abs_rl/fast_abs_rl/model/rnn.py", line 41, in lstm_encoder
    lstm_out = reorder_sequence(lstm_out, reorder_ind, lstm.batch_first)
  File "/home/project/fast_abs_rl/fast_abs_rl/model/util.py", line 58, in reorder_sequence
    sorted_ = sequence_emb.index_select(index=order, dim=batch_dim)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58

**Comment by ChenRocks** [comment]
I haven't observed any OOM error (using the same GPU) with the default hyper-parameters and following the training procedure in the paper on the CNN/DM dataset. 

Looks like OOM happened in the abstractor. And from the logging message it seems like you didn't train extractor and abstractor with ML objective till converge. Could you first try that if it helps? My hypothesis is that the abstractor is generating sentences that are too long (and it keeps all attention activations in memory). A well-trained abstractor should generate short, concise sentences. Meanwhile I will also take a look at the code for potential memory usage optimization. Thanks.

**Comment by zfang** [comment]
I was doing some experiment with large size pretrained embeddings (e.g. 1024). After running into OOM error during RL training on Amazon EC2 p2.8xlarge, using batch size 8 helped.

**Comment by ChenRocks** [comment]
pls ignore the above refs (mistakes)

@QuietWoods please let us know if the suggestions solve the OOM issue.

**Comment by ChenRocks** [comment]
Thanks, I think I have a guess on the reason of OOM.

The Abstractor decodes all extracted sentences in *1 single batch*.
In the beginning of RL training, the Extractor would try to extract much more sentences than needed. In your case, it might extract hundreds of them. So even you use a batch size of 1, the abstractor is actually decoding hundreds of sentence and results in OOM.
To verify this, you could start with putting a breakpoint at this line
https://github.com/ChenRocks/fast_abs_rl/blob/48281030c41b988cad00988fa7e3f5ed62f92058/rl.py#L64
and check the length of extracted sentence list `len(ext_sents)`

You will need to make modifications accordingly for your own dataset. If it is a publicly available dataset, please share a link to it and I might be able to give you some suggestions. Also, feel free to reply for further discussion on possible ideas to modify the code for your application.

**Comment by QuietWoods** [comment]
Thanks, you are right. the length of extracted sentence list is about 2000 in 4 single batch.
Can I restrict the Extractor from extracting the first 50 or 100 sentences of the article?
Because according to "make_extraction_labels.py", I found important sentences in the first 100 sentences. My dataset is not public. It is a text in a specific field, the Chinese patent application specification, and the abstract  is manually labeled. for details, see [1010.txt](https://github.com/ChenRocks/fast_abs_rl/files/2238672/1010.txt).this is a json file. I have an idea, if the article is cut according to the comma, the compute_rouge_l in the extractor performs very well. But it will make the number of short sentences rise sharply. Can you give me some suggestions? Thank you!

**Comment by ChenRocks** [comment]
I think in your case setting an upper limit on number of sentences is reasonable.
Alternatively, you can change line 64 in my above reply to a for loop like this:
```python
 summaries = concat(abstractor(ext_sents[i: i+x]) for i in range(0, len(ext_sents), x))
```
so that the abstractor doesn't take too much memory (at the cost of the time overhead of looping thru the sentences).

I would suggest the latter approach. Let me know if the above modification solves the memory issue.

Since this is somewhat task/dataset specific change, I won't update the code for it. However, feel free to fork the repo and enhance the functionalities. If you would like to share with others, feel free to submit pull requests for adding new features.

For splitting the article to sentences, I think there are several possible way to do it but it will highly depend on the dataset/language and your overall goal. The best suggestion I have is to run experiments and tune based on a dev dataset. (BTW, since your dataset looks very different from the CNN/DM, I would suggest to also tune the hyper-parameters)

**Comment by ChenRocks** [comment]
Cool! I'm happy to see it works. (I forgot `concat` gives iterator not list. Sorry about that.)
Thanks for your reply, this could help other having same issue on ultra-long document datasets.

Since the OOM issue is mainly due to nature of a very different dataset, I don't plan to change the repo for now. Although I would expect a lot more tuning need to be done for your dataset, that would fall beyond the scope of a github issue. Therefore, closing this upon resolving the initial OOM issue.
