### ISSUE TITLE
Possible bug in compute_rouge_n & compute_rouge_l & compute_rouge_l_summ

### ISSUE THREAD

**Issue by QuietWoods** [ChenRocks/fast_abs_rl#9]
https://github.com/ChenRocks/fast_abs_rl/blob/9e6c45d4b6bff87b221e6b06a64eb7142e7b2c27/metric.py#L33-L38
I assume this is  intended:
     if mode == 'p':
            &nbsp;&nbsp; &nbsp;&nbsp;score = precision
        **elif** mode == 'r':
            &nbsp;&nbsp; &nbsp;&nbsp; score = recall
        else:
            &nbsp;&nbsp;  &nbsp;&nbsp;score = f_score

**Comment by ChenRocks** [comment]
Thanks for pointing this out! Fixed in a04b073

Note that this does not affect the pretrained models since we use F-1 scores as the reward. And for the result we use official perl ROUGE package
